### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by michaelliu1210** [HenryPersonalWeb/HenryPersonalWeb.github.io#2]
Henry L?

**Comment by michaelliu1210** [comment]
forked

**Comment by HenryPersonalWeb** [comment]
?



在 2022-07-11 19:15:19，"michaelliu1210" ***@***.***> 写道：

forked

**Comment by HenryPersonalWeb** [comment]
yes



在 2022-07-11 19:15:13，"michaelliu1210" ***@***.***> 写道：

Henry L?

**Comment by HenryPersonalWeb** [comment]
!!!

**Comment by HenryPersonalWeb** [comment]
不就是Link吗

**Comment by HenryPersonalWeb** [comment]
你想干嘛

**Comment by HenryPersonalWeb** [comment]
@michaelliu1210 你这网站是Javascript搞出来的吗

**Comment by HenryPersonalWeb** [comment]
？？？

**Comment by michaelliu1210** [comment]
> ？？？

差不多吧

**Comment by michaelliu1210** [comment]
> @michaelliu1210 你这网站是Javascript搞出来的吗

其实是html
只不过背景动画是js
但是js部分太长了
导致系统以为这是js page = =

**Comment by michaelliu1210** [comment]
> ？？？

然后你点点看welcome

**Comment by michaelliu1210** [comment]
我close issue 了嗷

**Comment by HenryPersonalWeb** [comment]
哦哦



在 2022-07-11 21:24:25，"michaelliu1210" ***@***.***> 写道：

我close issue 了嗷
