### ISSUE TITLE
WHY DID YOU CHANGE YOUR README FILE BACK

### ISSUE THREAD

**Issue by michaelliu1210** [HenryPersonalWeb/HenryPersonalWeb.github.io#5]
*BRUH*

**Comment by HenryPersonalWeb** [comment]
？咋地力， 发在Profile里面

**Comment by michaelliu1210** [comment]
I need to update

**Comment by michaelliu1210** [comment]
plz commit my request

**Comment by HenryPersonalWeb** [comment]
Where? I didn't see any commits?



At 2022-07-25 19:19:25, "michaelliu1210" ***@***.***> wrote:

plz commit my request
